apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-normas-industriais
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-normas-industriais
  template:
    metadata:
      labels:
        app: api-normas-industriais
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sigo-normas
        image: docker.io/brunoferreirag/api-normas-industriais:latest
        ports:
        - containerPort: 8007
          name: api-normas
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "256m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-normas-industriais
spec:
  type: LoadBalancer 
  ports:
    - name: api-normas
      protocol: TCP
      port: 8007
  selector:
    app: api-normas-industriais  
---
